### ISSUE TITLE
Programm crashes after selecting source video

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer-ui#26]
When selecting the source video the program crashes.

D:\PC>java -jar configurationeditor-0.2-all.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
mrt 04, 2017 10:12:53 AM com.senorpez.replayenhancer.configurationeditor.ConfigurationEditor lambda$main$0
SEVERE: Exception in thread: Thread[JavaFX Application Thread,5,main]

**Comment by SenorPez** [comment]
Still working on this. I managed to recreate it (it didn't happen in my testing), and despite adding the requested loggers to the JAR, it's still crashing. I hate Java sometimes.

**Comment by SenorPez** [comment]
Fixed with 0.2.1 release.
