### ISSUE TITLE
Character conversion with drivers

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer-ui#4]
Reading the telemetry file gives me a driver named "Archie619no"
Saving the configuration it writes "Archie619\u0000no" in the configuration file.

Running replayenhancer I get the error:
```
michel@SRV-VM-UBUNTU:~/replayenhancer$ replayenhancer -s race1-Spa_ok.json
Traceback (most recent call last):
  File "/usr/local/bin/replayenhancer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/__init__.py", line 240, in main
    sync=args.sync)
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/__init__.py", line 207, in make_video
    Image.fromarray(pcre_series_champion.to_frame()).save(
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/StaticBase.py", line 60, in to_frame
    return PIL_to_npimage(self._make_material().convert('RGBA'))
  File "/usr/local/lib/python3.5/dist-packages/replayenhancer/DefaultCards.py", line 478, in _make_material
    self._name_lookup[entry.driver_name])
KeyError: 'Archie619no'
```
Chancing manual the name later on in the configuration file to Archie619no resolves the error.

**Comment by SenorPez** [comment]
Can you ZIP up the telemetry data and send it to me? I'm trying to figure out why the parsing is getting it wrong!

**Comment by SenorPez** [comment]
OMG OMG OMG OMG OMG!

First, I managed to recreate this on my own, so I don't need the telemetry data.

But second, and more importantly, I can see what's causing it.

One of the biggest headaches has always been "dirty data." If a "driver slot" in the telemetry has the name "Sarah," and that person drops out and is replaced by "Bob", the telemetry will actually show "Bob"'s name as "Bobah"... the characters past the length of the new name remain.

However, I'm now seeing that it's ACTUALLY being listed as "Bob\u0000ah". So with the proper logic, I can see where the "clean" data ends and the "dirty" data begins!

I'll fix this in the next RC, too.

**Comment by Michel-NL** [comment]
Glad you find it :)
But I don't recall that people left the session. Do you mean drivers switching from positions?

**Comment by Michel-NL** [comment]
You solved it 👍 
This bug could be closed.
