### ISSUE TITLE
Video end time needs to be seconds instead of minutes

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer-ui#7]
If you save the configuration then it saves the end time as minutes, but ReplayEnhancer needs it in seconds.
Think this could be related to the error message in #5 

Needs to be:
 "video_skipend" : 5160.0 **seconds**
  "video_skipstart" : 19.38 **minutes**

**Comment by Michel-NL** [comment]
Could it be that skipstart also needs to be in seconds?

**Comment by SenorPez** [comment]
Trying to figure out what you mean:

In the JSON file, `video_skipstart` and `video_skipend` are expressed in seconds. (They're also misnamed, but it's way too much effort now to rename them. They should be just called `video_start` and `video_end`.)

In the UI, it should be converting those values to HH:MM:SS.ss values. It'll accept data in that format, too.

So if you want your video to start at 19 minutes, 38 seconds, you could enter 19:38 in the UI, and it should output 1178 (19 * 60 + 38) into the configuration file.

**Comment by Michel-NL** [comment]
Could it be some regional settings on my PC. Look at the video start time and notice the . (dot) instead of : 

![untitled-1](https://cloud.githubusercontent.com/assets/16852542/20811420/e83af3d6-b80d-11e6-9fee-a50d95284838.jpg)

**Comment by Michel-NL** [comment]
Ok I was thinking that the first character is HH:MM:SS
My computer is seeing it as MM:SS.(??)

![untitled-2](https://cloud.githubusercontent.com/assets/16852542/20811750/2d15f73e-b80f-11e6-816a-94c4fbf11613.jpg)

**Comment by SenorPez** [comment]
It's actually quite smart, to save you from typing too many zeros. The behavior shown in your screenshots is actually correct.

SS.sss is seconds, and can actually be any number. If you wanted to enter 1178.0 there, it'd take it.
MM:SS.sss is minutes and seconds.
HH:MM:SS.sss is the full hours, minutes, and seconds.
